---
- name: disable selinux
  selinux:
    state: disabled
  register: selinux_result

#- name: reboot for selinux
#  shell: "sleep 2 && reboot"
#  async: 1
#  poll: 0
#  when: selinux_result.reboot_required
#
#- name: waiting for halt
#  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
#  when: selinux_result.reboot_required
#
#- name: waiting for start
#  local_action: wait_for host={{ inventory_hostname }} port=22 state=started
#  when: selinux_result.reboot_required

- name: disable firewalld
  service:
    state: stopped
    name: firewalld
    enabled: no

- name: add user ( admin )
  user:
    name: "{{ ssh_loosely_username }}"
    password: "{{ ssh_loosely_userpass | password_hash('sha512') }}"

#- name: add user can sudo


- name: edit sshd_config
  replace:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    backup: yes
  with_items:
    - regexp: '^PasswordAuthentication no'
      replace: 'PasswordAuthentication yes'
  notify: Restart sshd

