---
- name: disable selinux
  selinux:
    state: disabled
  register: selinux_result

#- name: reboot for selinux
#  shell: "sleep 2 && reboot"
#  async: 1
#  poll: 0
#  when: selinux_result.reboot_required
#
#- name: waiting for halt
#  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
#  when: selinux_result.reboot_required
#
#- name: waiting for start
#  local_action: wait_for host={{ inventory_hostname }} port=22 state=started
#  when: selinux_result.reboot_required

- name: disable firewalld
  service:
    state: stopped
    name: firewalld
    enabled: no

- name: "add user ( {{ ssh_loosely_username }} )"
  user:
    name: "{{ ssh_loosely_username }}"
    password: "{{ ssh_loosely_userpass | password_hash('sha512') }}"
    update_password: on_create

- name: add user can sudo
  lineinfile:
    path: "/etc/sudoers.d/{{ ssh_loosely_username }}"
    line: "{{ ssh_loosely_username }}   ALL=(ALL)   NOPASSWD: ALL"
    create: yes
    state: present

- name: add LANG for {{ ssh_loosely_username }}
  lineinfile:
    path: "/home/{{ ssh_loosely_username }}/.bash_profile"
    line: "export LANG=ja_JP.utf8"
    state: present

- name: edit sshd_config
  replace:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    backup: yes
  with_items:
    - regexp: '^PasswordAuthentication no'
      replace: 'PasswordAuthentication yes'
  notify: Restart sshd

